# This is the name of the workflow
name: Deploy Website

# This defines when the workflow should run
on:
  push:
    branches:
      - main # Or your main branch name (e.g., main, master)

# This defines the jobs that will run
jobs:
  deploy:
    # The type of runner the job will run on
    runs-on: ubuntu-latest

    # Steps define the sequence of actions that will be executed
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access your code.
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up Node.js (if you have a Node.js website)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your desired Node.js version

      # Install dependencies (if you have them)
      - name: Install dependencies
        run: npm install # Or yarn install, or pnpm install

      # Build the website (if you have a build step)
      - name: Build website
        run: npm run build # Or yarn build, or pnpm build

      # Deploy to GitHub Pages (example - adjust as needed)
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: dist # Name of the artifact containing your built website files
          # Optional: Specify a custom domain
          # cname: yourdomain.com
        #if: github.ref == 'refs/heads/main' # Only deploy from main branch

      # Upload artifacts (for debugging or later use)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-files
          path: ./dist # Or the directory containing your built website 